### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by p1nkyy** [iconoclasthero/Hoopla-DL#1]
1. Hi, is it possible to save our credential so the script doesn't need to ask every time I need to process a book?

2. If I downloaded book A, moved it to another folder, then borrowed book B & C, ran the script again, will book A be re-downloaded?

3. When I tried to obtain several unborrowed books at once, it successfully borrowed them but only manage to download the first title only and failed to process the other 2 with this error message below. I then processed the other 2 one by one and successful. What did I do wrong?
![image](https://user-images.githubusercontent.com/7593831/187067077-5f8fb257-912f-42ab-834d-99e4755f61a1.png)

I'm a newbie in using this kind of script so sorry if some of my questions is too basic. Thanks before for this wonderful script!

**Comment by iconoclasthero** [comment]
So, I have no idea.  I didn't write this, I don't understand the code since I don't use powershell, etc.,  I've basically been running this in a PS emulator in bash under Ubuntu so there's probably going to be some OS differences as well.

If you look at the beginning of the code, I believe there are some explanations/examples of how to use it.

**Comment by p1nkyy** [comment]
OK, can you pls point me out the author so I can ask questions to him? Thanks.

**Comment by iconoclasthero** [comment]
No...I picked up the code from a private website and I do not have the author's contact information.  You can see if there's anything to that effect in the code itself.

**Comment by iconoclasthero** [comment]
Also, you need to get ffmpeg.  This is not the place to figure out how to do that in Windows.  You need to go to some support site for ffmpeg on Windows, either to download a static build (probably all you need) or to compile it yourself on Windows.  If you are only downloading audiobooks, the rest of the applications are moot...and if you're not, I have zero idea since I've really only ever used hoopla-dl to convert audiobooks.

**Comment by p1nkyy** [comment]
ffmpeg is only needed for audiobooks and my use is only for e-books hence I didn't move it to this folder. I already have ffmpeg and I can read well thanks very much but the readmd doesn't contain much and I believe there must be a bug but OK if you don't create this, I won't bug you any more. Pls update if it's updated someday. Thanks.
